# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"E\n\x0c\x44\x65layedReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12$\n\x07request\x18\x02 \x03(\x0b\x32\x13.greet.HelloRequest\">\n\x0e\x43heckInRequest\x12\x0c\n\x04nric\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\"-\n\x0f\x43heckOutRequest\x12\x0c\n\x04nric\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\" \n\rCheckResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"3\n\x0f\x41\x64\x64GroupRequest\x12\x0c\n\x04nric\x18\x01 \x01(\t\x12\x12\n\nnricMember\x18\x02 \x01(\t\"\"\n\x12\x44\x65leteGroupRequest\x12\x0c\n\x04nric\x18\x01 \x01(\t\"C\n\x13\x43heckInGroupRequest\x12\x0c\n\x04nric\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\"2\n\x14\x43heckOutGroupRequest\x12\x0c\n\x04nric\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t2\xf5\x04\n\x07Greeter\x12\x32\n\x08SayHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply\x12;\n\x0fParrotSaysHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply0\x01\x12\x43\n\x15\x43hattyClientSaysHello\x12\x13.greet.HelloRequest\x1a\x13.greet.DelayedReply(\x01\x12>\n\x10InteractingHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply(\x01\x30\x01\x12\x36\n\x07\x43heckIn\x12\x15.greet.CheckInRequest\x1a\x14.greet.CheckResponse\x12\x38\n\x08\x43heckOut\x12\x16.greet.CheckOutRequest\x1a\x14.greet.CheckResponse\x12<\n\x08\x41\x64\x64Group\x12\x16.greet.AddGroupRequest\x1a\x14.greet.CheckResponse(\x01\x30\x01\x12>\n\x0b\x44\x65leteGroup\x12\x19.greet.DeleteGroupRequest\x1a\x14.greet.CheckResponse\x12@\n\x0c\x43heckInGroup\x12\x1a.greet.CheckInGroupRequest\x1a\x14.greet.CheckResponse\x12\x42\n\rCheckOutGroup\x12\x1b.greet.CheckOutGroupRequest\x1a\x14.greet.CheckResponseb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_DELAYEDREPLY = DESCRIPTOR.message_types_by_name['DelayedReply']
_CHECKINREQUEST = DESCRIPTOR.message_types_by_name['CheckInRequest']
_CHECKOUTREQUEST = DESCRIPTOR.message_types_by_name['CheckOutRequest']
_CHECKRESPONSE = DESCRIPTOR.message_types_by_name['CheckResponse']
_ADDGROUPREQUEST = DESCRIPTOR.message_types_by_name['AddGroupRequest']
_DELETEGROUPREQUEST = DESCRIPTOR.message_types_by_name['DeleteGroupRequest']
_CHECKINGROUPREQUEST = DESCRIPTOR.message_types_by_name['CheckInGroupRequest']
_CHECKOUTGROUPREQUEST = DESCRIPTOR.message_types_by_name['CheckOutGroupRequest']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

DelayedReply = _reflection.GeneratedProtocolMessageType('DelayedReply', (_message.Message,), {
  'DESCRIPTOR' : _DELAYEDREPLY,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.DelayedReply)
  })
_sym_db.RegisterMessage(DelayedReply)

CheckInRequest = _reflection.GeneratedProtocolMessageType('CheckInRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKINREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.CheckInRequest)
  })
_sym_db.RegisterMessage(CheckInRequest)

CheckOutRequest = _reflection.GeneratedProtocolMessageType('CheckOutRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUTREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.CheckOutRequest)
  })
_sym_db.RegisterMessage(CheckOutRequest)

CheckResponse = _reflection.GeneratedProtocolMessageType('CheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKRESPONSE,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.CheckResponse)
  })
_sym_db.RegisterMessage(CheckResponse)

AddGroupRequest = _reflection.GeneratedProtocolMessageType('AddGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDGROUPREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.AddGroupRequest)
  })
_sym_db.RegisterMessage(AddGroupRequest)

DeleteGroupRequest = _reflection.GeneratedProtocolMessageType('DeleteGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEGROUPREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.DeleteGroupRequest)
  })
_sym_db.RegisterMessage(DeleteGroupRequest)

CheckInGroupRequest = _reflection.GeneratedProtocolMessageType('CheckInGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKINGROUPREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.CheckInGroupRequest)
  })
_sym_db.RegisterMessage(CheckInGroupRequest)

CheckOutGroupRequest = _reflection.GeneratedProtocolMessageType('CheckOutGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKOUTGROUPREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.CheckOutGroupRequest)
  })
_sym_db.RegisterMessage(CheckOutGroupRequest)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=22
  _HELLOREQUEST._serialized_end=68
  _HELLOREPLY._serialized_start=70
  _HELLOREPLY._serialized_end=99
  _DELAYEDREPLY._serialized_start=101
  _DELAYEDREPLY._serialized_end=170
  _CHECKINREQUEST._serialized_start=172
  _CHECKINREQUEST._serialized_end=234
  _CHECKOUTREQUEST._serialized_start=236
  _CHECKOUTREQUEST._serialized_end=281
  _CHECKRESPONSE._serialized_start=283
  _CHECKRESPONSE._serialized_end=315
  _ADDGROUPREQUEST._serialized_start=317
  _ADDGROUPREQUEST._serialized_end=368
  _DELETEGROUPREQUEST._serialized_start=370
  _DELETEGROUPREQUEST._serialized_end=404
  _CHECKINGROUPREQUEST._serialized_start=406
  _CHECKINGROUPREQUEST._serialized_end=473
  _CHECKOUTGROUPREQUEST._serialized_start=475
  _CHECKOUTGROUPREQUEST._serialized_end=525
  _GREETER._serialized_start=528
  _GREETER._serialized_end=1157
# @@protoc_insertion_point(module_scope)
